version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql-bank-transaction
    restart: always
    ports:
      - 3306:3306
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  queue:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-bank-transaction
    restart: always
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/

  cache:
    image: redis:6.2-alpine
    container_name: redis-bank-transaction
    restart: always
    ports:
      - 6379:6379
      